pool_size: 1
storages:
  local_storage:
    ==: LocalStorage
    root:
      - './WaybackBackups'
# ftp_server:
#   ==: FtpStorage
#   host: 127.0.0.1
#   port: 22
#   ftps: false
#   ftpes: false
#   user: test
#   password: test
#   root: '/usr/share/wayback-backups'
compressor:
  - ==: zip
    level: 9
    encrypt: false
    password: example
backups:
  file_backup:
    ==: File
    root: './'
    excludes:
      - 'WaybackBackups'
      - 'assets'
      - 'cache'
      - 'libraries'
      - 'libs'
      - 'logs'
      - 'session.lock'
    skip_large_file: true
    large_file: 64.000
    incremental: true
policies:
  clean_oldest:
    ==: CleanOldest
  clean_latest:
    ==: CleanLatest
  clean_exceed:
    ==: CleanExceed
    max_backups: 10
  abandon:
    ==: Abandon
  retry3:
    ==: Retry
    max_retry: 3
    retry_period: 60
  retry1:
    ==: Retry
    max_retry: 1
    retry_period: 1
tasks:
  backup_file:
    ==: Transfer
    from: file_backup
    to: local_storage
    no_enough_space: [clean_oldest, retry1]
  # next: upload_ftp
#  upload_ftp:
#    ==: Transfer
#    from: local_storage
#    to: ftp_server
#    connection_fail: [abandon]
#    on_complete: [clean_latest]
schedules:
  timer_backup:
    ==: Period
    time_unit: MINUTES
    initial: 60
    period: 60
    task: backup_file
rollback:
  ==: Rollback
  from: [local_storage]
  to: file_backup
